"""likes

Revision ID: 00ea6f26199e
Revises: 5898046ba82e
Create Date: 2021-07-30 15:10:50.671647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ea6f26199e'
down_revision = '5898046ba82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prof',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('netid', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('keywords', sa.String(length=1024), nullable=True),
    sa.Column('research_interests', sa.String(length=1024), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('advising', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('netid')
    )
    op.create_index(op.f('ix_prof_name'), 'prof', ['name'], unique=False)
    op.create_table('prof_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('prof_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['prof_id'], ['prof.netid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.netid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_profdb_name', table_name='profdb')
    op.drop_table('profdb')
    op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.create_table('profdb',
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('netid', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('research_interests', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('room', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('advising', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('netid', name='profdb_pkey')
    )
    op.create_index('ix_profdb_name', 'profdb', ['name'], unique=False)
    op.drop_table('prof_like')
    op.drop_index(op.f('ix_prof_name'), table_name='prof')
    op.drop_table('prof')
    # ### end Alembic commands ###
