"""empty message

Revision ID: 18a3ca4452af
Revises: 00ea6f26199e
Create Date: 2021-08-19 19:41:32.319844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a3ca4452af'
down_revision = '00ea6f26199e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prof', sa.Column('picture', sa.String(length=256), nullable=True))
    op.add_column('prof', sa.Column('projects', sa.PickleType(), nullable=True))
    op.add_column('prof', sa.Column('publications', sa.PickleType(), nullable=True))
    op.add_column('prof', sa.Column('citations', sa.Integer(), nullable=True))
    op.add_column('prof', sa.Column('hindex', sa.Integer(), nullable=True))
    op.drop_column('prof', 'research_interests')
    op.drop_column('prof', 'room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prof', sa.Column('room', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('prof', sa.Column('research_interests', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('prof', 'hindex')
    op.drop_column('prof', 'citations')
    op.drop_column('prof', 'publications')
    op.drop_column('prof', 'projects')
    op.drop_column('prof', 'picture')
    # ### end Alembic commands ###
