"""profdb

Revision ID: 201908f136a6
Revises: 
Create Date: 2021-07-23 23:18:53.484936

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '201908f136a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('netid', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('keywords', sa.String(length=120), nullable=True),
    sa.Column('research_interests', sa.String(length=120), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('advising', sa.Boolean(), nullable=True),
    sa.Column('__ts_vector__', app.models.TSVector(), sa.Computed("to_tsvector('english', name || ' ' || department || ' ' || email || ' ' || keywords)", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profdb_name'), 'profdb', ['name'], unique=False)
    op.create_index('ix_profs_tsv', 'profdb', ['__ts_vector__'], unique=False, postgresql_using='gin')
    op.drop_index('ix_profs_name', table_name='profs')
    op.drop_table('profs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('room', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('advising', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='profs_pkey')
    )
    op.create_index('ix_profs_name', 'profs', ['name'], unique=False)
    op.drop_index('ix_profs_tsv', table_name='profdb', postgresql_using='gin')
    op.drop_index(op.f('ix_profdb_name'), table_name='profdb')
    op.drop_table('profdb')
    # ### end Alembic commands ###
