"""empty message

Revision ID: 2bda9b71d274
Revises: c0bfd5568876
Create Date: 2021-08-21 13:05:55.865051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bda9b71d274'
down_revision = 'c0bfd5568876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prof', sa.Column('courses', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prof', 'courses')
    # ### end Alembic commands ###
