"""empty message

Revision ID: 4722c49fbb24
Revises: 2bda9b71d274
Create Date: 2021-08-22 17:58:48.546828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4722c49fbb24'
down_revision = '2bda9b71d274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prof', sa.Column('department_color', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prof', 'department_color')
    # ### end Alembic commands ###
