"""profdb

Revision ID: b9eff9c661fa
Revises: 201908f136a6
Create Date: 2021-07-23 23:30:33.770547

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = 'b9eff9c661fa'
down_revision = '201908f136a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profdb', 'netid',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('profdb', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profdb', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('profdb', 'netid',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
