"""empty message

Revision ID: c0bfd5568876
Revises: 18a3ca4452af
Create Date: 2021-08-19 20:11:55.405407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bfd5568876'
down_revision = '18a3ca4452af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prof', sa.Column('fingerprints', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prof', 'fingerprints')
    # ### end Alembic commands ###
