"""user

Revision ID: c55d44a45a3e
Revises: 0c8aed20b4ec
Create Date: 2021-07-29 17:35:27.190655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55d44a45a3e'
down_revision = '0c8aed20b4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
